name: validation 🔐

on: workflow_dispatch

jobs:
  check_if_license_exist:
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    steps:
      - name: Fail - No License XX
        if: ${{ !startsWith(env.UNITY_LICENSE, '<') }}
        run: exit 1

  check_variables:
    needs: check_if_license_exist
    runs-on: ubuntu-latest
    steps:
      - name: Check Variables
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        run: |
          if [[ -z "${UNITY_LICENSE}" ]]; then
            echo "UNITY_LICENSE is not set. Please set the secret in the repository settings."
            exit 1
          fi
          if [[ -z "${UNITY_EMAIL}" ]]; then
            echo "UNITY_EMAIL is not set. Please set the secret in the repository settings."
            exit 1
          fi
          if [[ -z "${UNITY_PASSWORD}" ]]; then
            echo "UNITY_PASSWORD is not set. Please set the secret in the repository settings."
            exit 1
          fi  

  validation:
    needs: check_variables
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Unity - Activate
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        uses: game-ci/unity-activate@v2.0.0
        with:
          unity-version: 2019.4.28f1
          unity-serial: ${{ env.UNITY_LICENSE }}
          unity-username: ${{ env.UNITY_USERNAME }}
          unity-password: ${{ env.UNITY_PASSWORD }}